/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
              "on-error-container": "var(--color-on-error-container)",
              "surface-container": "var(--color-surface-container)",
              "inverse-surface": "var(--color-inverse-surface)",
              "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
              "on-secondary-container": "var(--color-on-secondary-container)",
              "surface-tint": "var(--color-surface-tint)",
              "surface-variant": "var(--color-surface-variant)",
              "surface-dim": "var(--color-surface-dim)",
              "tertiary-fixed": "var(--color-tertiary-fixed)",
              "on-background": "var(--color-on-background)",
              "on-primary-fixed": "var(--color-on-primary-fixed)",
              "background": "var(--color-background)",
              "on-tertiary-container": "var(--color-on-tertiary-container)",
              "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
              "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
              "primary-container": "var(--color-primary-container)",
              "error-container": "var(--color-error-container)",
              "on-surface-variant": "var(--color-on-surface-variant)",
              "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
              "on-primary-container": "var(--color-on-primary-container)",
              "inverse-on-surface": "var(--color-inverse-on-surface)",
              "surface-container-low": "var(--color-surface-container-low)",
              "surface": "var(--color-surface)",
              "primary-fixed-dim": "var(--color-primary-fixed-dim)",
              "outline": "var(--color-outline)",
              "on-surface": "var(--color-on-surface)",
              "secondary-container": "var(--color-secondary-container)",
              "surface-container-high": "var(--color-surface-container-high)",
              "primary-fixed": "var(--color-primary-fixed)",
              "error": "var(--color-error)",
              "primary": "var(--color-primary)",
              "on-tertiary": "var(--color-on-tertiary)",
              "on-secondary": "var(--color-on-secondary)",
              "tertiary": "var(--color-tertiary)",
              "tertiary-container": "var(--color-tertiary-container)",
              "secondary-fixed": "var(--color-secondary-fixed)",
              "surface-container-lowest": "var(--color-surface-container-lowest)",
              "secondary": "var(--color-secondary)",
              "outline-variant": "var(--color-outline-variant)",
              "on-error": "var(--color-on-error)",
              "surface-bright": "var(--color-surface-bright)",
              "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
              "inverse-primary": "var(--color-inverse-primary)",
              "on-secondary-fixed": "var(--color-on-secondary-fixed)",
              "surface-container-highest": "var(--color-surface-container-highest)",
              "on-primary": "var(--color-on-primary)"
      },
      "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
